CREATE SCHEMA IF NOT EXISTS plugin;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS plugin.users (
    user_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(200) NOT NULL UNIQUE
);
